module.exports = [
{"id": 1,"name": "Capital Investment Planning","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 2,"name": "Intergovernmental Transfers","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 3,"name": "Developer Exactions and Impact Fees","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND"}, 
{"id": 4,"name": "Betterment Levies","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND"}, 
{"id": 5,"name": "Business Improvement Districts","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CADASTRE": "HAS_CADASTRE"}, 
{"id": 6,"name": "Tax Increment Financing (TIF)","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CAP_MKTS": "ACCESS_TO_CAP_MKTS","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE"}, 
{"id": 7,"name": "Payment-in-Lieu-of-Taxes (PILOT) 7","phase": "financing","CAP_MKTS": "ACCESS_TO_CAP_MKTS","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE"}, 
{"id": 8,"name": "Special Assessment Districts","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CAP_MKTS": "ACCESS_TO_CAP_MKTS","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE"}, 
{"id": 9,"name": "Density Bonus (inclusionary zoning)","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CADASTRE": "HAS_CADASTRE","ZONING": "HAS_ZONING"}, 
{"id": 10,"name": "Upzoning","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE","ZONING": "HAS_ZONING"}, 
{"id": 11,"name": "Transferable Development Rights","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CADASTRE": "HAS_CADASTRE","ZONING": "HAS_ZONING"}, 
{"id": 12,"name": "Direct Grants","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND"}, 
{"id": 13,"name": "Low-Cost Loans","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND"}, 
{"id": 14,"name": "Tax Incentives","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE","ZONING": "HAS_ZONING"}, 
{"id": 15,"name": "Sale or Long-Term Lease of a Municipally-Owned Site through an Arm's Length Transaction","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 16,"name": "Land Swaps","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 17,"name": "Sale or Long-Term Lease through a Strategic Negotiated Transaction","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 18,"name": "Public Land as an \"In Kind\" Payment in Return for Construction of Public Infrastructure","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 19,"name": "Public Land as an Equity Contribution toward a Joint Venture 19","phase": "financing","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 20,"name": "Land Readjustment","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","CADASTRE": "HAS_CADASTRE","LAND_ASSEMBLAGE": "FRAGMENTED_LAND","ZONING": "HAS_ZONING","EXISTING_COMMUNITY": "HAS_EXISTING_COMMUNITY"}, 
{"id": 21,"name": "Urban Redevelopment","phase": "financing","LAND_OWNERSHIP": "PRIVATE_LAND","LAND_ASSEMBLAGE": "FRAGMENTED_LAND","ZONING": "HAS_ZONING"}, 
{"id": 22,"name": "Land Sharing","phase": "planning","INFROMAL_SETTLE": "HAS_INFORMAL_SETTLEMENTS"}, 
{"id": 23,"name": "Expropriation","phase": "planning","LAND_OWNERSHIP": "PRIVATE_LAND"}, 
{"id": 24,"name": "The Right of Preemption","phase": "planning","LAND_OWNERSHIP": "PRIVATE_LAND","CADASTRE": "HAS_CADASTRE","EXISTING_COMMUNITY": "HAS_EXISTING_COMMUNITY"}, 
{"id": 25,"name": "Land Administration","phase": "planning","CADASTRE": "NO_CADASTRE"}, 
{"id": 26,"name": "Valuation of Public Land","phase": "planning","LAND_OWNERSHIP": "PUBLIC_LAND"}, 
{"id": 27,"name": "Progressive Taxation of Vacant Land","phase": "planning","LAND_OWNERSHIP": "PRIVATE_LAND","TAX": "HAS_TAX","CADASTRE": "HAS_CADASTRE","ZONING": "HAS_ZONING"}, 
{"id": 28,"name": "Zoning and Land Use Planning","phase": "planning","ZONING": "NO_ZONING"}, 
{"id": 29,"name": "Charettes","phase": "planning","INFROMAL_SETTLE": "HAS_INFORMAL_SETTLEMENTS"}, 
{"id": 30,"name": "Using Technology for Public Participation","phase": "planning"}, 
{"id": 31,"name": "Site Assessment","phase": "planning","ENVIRON_CONCERNS": "HAS_ENVIRON_CONCERNS"}, 
{"id": 32,"name": "Site Investigation","phase": "planning","ENVIRON_CONCERNS": "HAS_ENVIRON_CONCERNS"}, 
{"id": 33,"name": "Environmental Impact Assessment (EIA) and Site Remediation Plan","phase": "planning","ENVIRON_CONCERNS": "HAS_ENVIRON_CONCERNS"}, 
{"id": 34,"name": "Tools to Mitigate the Undesirable Social Impacts of Urban Regeneration and Resettlement","phase": "planning","EXISTING_COMMUNITY": "HAS_EXISTING_COMMUNITY","INFROMAL_SETTLE": "HAS_INFORMAL_SETTLEMENTS"}, 
{"id": 35,"name": "Inclusionary Zoning","phase": "financing","EXISTING_COMMUNITY": "HAS_EXISTING_COMMUNITY","INFROMAL_SETTLE": "HAS_INFORMAL_SETTLEMENTS"}, 
{"id": 36,"name": "Housing Vouchers (or demand-side subsidies) as an Alternative to Inclusionary Zoning","phase": "financing","EXISTING_COMMUNITY": "HAS_EXISTING_COMMUNITY","INFROMAL_SETTLE": "HAS_INFORMAL_SETTLEMENTS"}, 
{"id": 37,"name": "Macro-Level Scoping","phase": "scoping"}, 
{"id": 38,"name": "Micro-Level Scoping","phase": "scoping"}, 
{"id": 39,"name": "The Planning Framework","phase": "planning"}, 
{"id": 40,"name": "Master Planning","phase": "planning"}, 
{"id": 41,"name": "Developing Design Standards","phase": "planning"}, 
{"id": 42,"name": "Setting the Scene","phase": "planning"}, 
{"id": 43,"name": "Defing the Implementation Process and Institutional Arrangements","phase": "planning"}, 
{"id": 44,"name": "Defining Early Wins","phase": "planning"}
]